//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingCastle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PingCastle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAKcAAAAgCAYAAAB3o2iMAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAhkSURBVHgB7VrNchvHEe6ZBSkmF+FikSFIe3VxTomRJyB4SHIU9QQkT/GN5BMAfAKSN98EPoHAoysHgU8gKCeXUylu+GdKuUAXiwaw0/l6d2e5ABY/lGFaVZ6vagHs/PT0zHzT3dMkkYODg4ODg4ODg4ODw28USj7+9cfyGb78oUpF63/6rtUc6vX1v6tEXKPxCOibL5+Sg8NHopB8+4MVDHKFQrBBTEfMXJkODveBzisUYhpYzb981wr6KqYnpoPDz8YQOR0xHT4V9JHTEdPhU4KNOUcTU3AW1IbKvv2r6nv/+z+ZHBxmiJicTM+NplYuMX8hPCl9/kK+fz+n94IgaNvypdLqFhtVfPvD+aG8L5ZWDpn042xfrfQxcegbUmt5snFKmjg5lTkK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrandLogo {
            get {
                return ResourceManager.GetString("BrandLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAABAAQAEBAAAAEAIABoBAAARgAAABgYAAABACAAiAkAAK4EAAAgIAAAAQAgAKgQAAA2DgAAMDAAAAEAIACoJQAA3h4AACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv4AABOZmAArjcQAJ43EACeNxAAnjcQAJ43EACd9gAAgAAAAAAAAAAAAAAADmZgAK5mYACr+AAAQAAAAA1VUABttoANLaaAD42mgA7dpoAO3aaADt2mgA7dpoAPHaaAD+2mkARAAAAADVVQAG2mgA4uVtAP/aaADR1VUABsxmAArdawD47XMA/+txAP/2dQD/9nUA//Z1AP/4dwD//4AA/9xnAF4AAAAAAAAAANtpAFz7eAD/5G0A/8xmAArGVQAJ0F0A7d5jAP/TYADk2mkArdppAK3aaQCt2WgAsNlpALfcaAAsAAAAAAAAAAAAAAAA2mkAWtpoAObodAALqjkACblEAO3RTgD/tkIApQAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportFavicon {
            get {
                return ResourceManager.GetString("ReportFavicon", resourceCulture);
            }
        }
    }
}
